name:                pcapng
version:             0.1.0.0
github:              "mgajda/pcapng"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  PCAP-NG and PCAP format reader and writer.

dependencies:
- base >= 4.7 && < 5
- bytestring
- conduit
- conduit-extra >= 1.3.0
- cereal
- cereal-conduit
- unliftio-core
- resourcet
- lens

library:
  source-dirs: src

executables:
  pcapng-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcapng

tests:
  pcapng-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcapng
    - directory
    - conduit
    - resourcet
    - hspec
    - hspec-core
    - filepath
    - QuickCheck
